version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: queue_db
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=queue_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=queue_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U queue_user -d queue_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: queue_backend
    build:
      context: .
      dockerfile: queue-service/Dockerfile
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__QueueDbContext=Host=db;Database=queue_db;Username=queue_user;Password=supersecretpassword
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    command: ["dotnet", "QueueService.dll"]

  frontend:
    container_name: queue_frontend
    build:
      context: ./queue-app
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  .postgres_data: